# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biaoge2UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bg2Form(object):
    def setupUi(self, bg2Form):
        bg2Form.setObjectName("bg2Form")
        bg2Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(bg2Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(bg2Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(bg2Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(bg2Form)

    def retranslateUi(self, bg2Form):
        _translate = QtCore.QCoreApplication.translate
        bg2Form.setWindowTitle(_translate("bg2Form", "Form"))
