# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biaogeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bgForm(object):
    def setupUi(self, bgForm):
        bgForm.setObjectName("bgForm")
        bgForm.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(bgForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(bgForm)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_search = QtWidgets.QPushButton(bgForm)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_2.addWidget(self.pushButton_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtWidgets.QTreeView(bgForm)
        self.treeView.setStyleSheet("font: 12pt \"3ds\";")
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.textEdit = QtWidgets.QTextEdit(bgForm)
        self.textEdit.setStyleSheet("font: 9pt \"3ds\";")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(bgForm)
        QtCore.QMetaObject.connectSlotsByName(bgForm)

    def retranslateUi(self, bgForm):
        _translate = QtCore.QCoreApplication.translate
        bgForm.setWindowTitle(_translate("bgForm", "Form"))
        self.pushButton_search.setText(_translate("bgForm", "搜索"))
